name : Communicating with Cliq

on:
  #you may add the events you like to get notified
  push:
    
jobs:
  test_name:
    runs-on: ubuntu-latest
    steps:
      - uses: Integrations-dev/CliqInformer@v1
        with:
          channel-endpoint: ${{ secrets.ENDPOINT }}
